name: mars_logging_android
description: 'Android implementation of the mars_logging plugin.'
version: 1.0.0-dev.1
repository: 'https://github.com/yanshouwang/mars_logging'
issue_tracker: 'https://github.com/yanshouwang/mars_logging/issues'
topics:
  - mars
  - logging

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  mars_logging_platform_interface: ^1.0.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^26.0.0

flutter:
  plugin:
    implements: mars_logging
    platforms:
      android:
        package: dev.zeekr.mars_logging_android
        pluginClass: MarsLoggingAndroidPlugin
        dartPluginClass: MarsLoggingAndroidPlugin
