// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class MarsLoggingError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "MarsLoggingError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? MarsLoggingError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum AppenderModeApi: Int {
  case async = 0
  case sync = 1
}

enum XLogLevelApi: Int {
  case all = 0
  case verbose = 1
  case debug = 2
  case info = 3
  case warning = 4
  case error = 5
  case fatal = 6
  case none = 7
}

enum CompressModeApi: Int {
  case zlib = 0
  case zstd = 1
}

enum CompressLevelApi: Int {
  case level1 = 0
  case level2 = 1
  case level3 = 2
  case level4 = 3
  case level5 = 4
  case level6 = 5
  case level7 = 6
  case level8 = 7
  case level9 = 8
}

private class MarsLoggingApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AppenderModeApi(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return XLogLevelApi(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CompressModeApi(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CompressLevelApi(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MarsLoggingApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppenderModeApi {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? XLogLevelApi {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CompressModeApi {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? CompressLevelApi {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class MarsLoggingApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MarsLoggingApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MarsLoggingApiPigeonCodecWriter(data: data)
  }
}

class MarsLoggingApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MarsLoggingApiPigeonCodec(readerWriter: MarsLoggingApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol XLogHostApi {
  func open(mode: AppenderModeApi, level: XLogLevelApi, logsDir: String, cacheDir: String, cacheDays: Int64, namePrefix: String, compressMode: CompressModeApi, compressLevel: CompressLevelApi, pubKey: String, useConsole: Bool, maxFileSize: Int64, maxAliveDuration: Int64) throws
  func flush(isSync: Bool) throws
  func close() throws
  func verbose(tag: String, message: String) throws
  func debug(tag: String, message: String) throws
  func info(tag: String, message: String) throws
  func warning(tag: String, message: String) throws
  func error(tag: String, message: String) throws
  func fatal(tag: String, message: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class XLogHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MarsLoggingApiPigeonCodec.shared }
  /// Sets up an instance of `XLogHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: XLogHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! AppenderModeApi
        let levelArg = args[1] as! XLogLevelApi
        let logsDirArg = args[2] as! String
        let cacheDirArg = args[3] as! String
        let cacheDaysArg = args[4] as! Int64
        let namePrefixArg = args[5] as! String
        let compressModeArg = args[6] as! CompressModeApi
        let compressLevelArg = args[7] as! CompressLevelApi
        let pubKeyArg = args[8] as! String
        let useConsoleArg = args[9] as! Bool
        let maxFileSizeArg = args[10] as! Int64
        let maxAliveDurationArg = args[11] as! Int64
        do {
          try api.open(mode: modeArg, level: levelArg, logsDir: logsDirArg, cacheDir: cacheDirArg, cacheDays: cacheDaysArg, namePrefix: namePrefixArg, compressMode: compressModeArg, compressLevel: compressLevelArg, pubKey: pubKeyArg, useConsole: useConsoleArg, maxFileSize: maxFileSizeArg, maxAliveDuration: maxAliveDurationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let flushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.flush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isSyncArg = args[0] as! Bool
        do {
          try api.flush(isSync: isSyncArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      flushChannel.setMessageHandler(nil)
    }
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { _, reply in
        do {
          try api.close()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
    let verboseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.verbose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      verboseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.verbose(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      verboseChannel.setMessageHandler(nil)
    }
    let debugChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.debug\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.debug(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      debugChannel.setMessageHandler(nil)
    }
    let infoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.info\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      infoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.info(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      infoChannel.setMessageHandler(nil)
    }
    let warningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.warning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      warningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.warning(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      warningChannel.setMessageHandler(nil)
    }
    let errorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.error\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      errorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.error(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      errorChannel.setMessageHandler(nil)
    }
    let fatalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging_darwin.XLogHostApi.fatal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fatalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.fatal(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fatalChannel.setMessageHandler(nil)
    }
  }
}
