// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class MarsLoggingError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "MarsLoggingError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? MarsLoggingError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum AppenderModeApi: Int {
  case async = 0
  case sync = 1
}

enum XLogLevelApi: Int {
  case all = 0
  case verbose = 1
  case debug = 2
  case info = 3
  case warning = 4
  case error = 5
  case fatal = 6
  case none = 7
}

private class MarsLoggingPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AppenderModeApi(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return XLogLevelApi(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MarsLoggingPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppenderModeApi {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? XLogLevelApi {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class MarsLoggingPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MarsLoggingPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MarsLoggingPigeonCodecWriter(data: data)
  }
}

class MarsLoggingPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MarsLoggingPigeonCodec(readerWriter: MarsLoggingPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol XLogApi {
  func open(mode: AppenderModeApi, logsDir: String, cacheDir: String, cacheDays: Int64, nameprefix: String, useConsole: Bool, level: XLogLevelApi) throws
  func flush(isSync: Bool) throws
  func close() throws
  func verbose(tag: String, message: String) throws
  func debug(tag: String, message: String) throws
  func info(tag: String, message: String) throws
  func warning(tag: String, message: String) throws
  func error(tag: String, message: String) throws
  func fatal(tag: String, message: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class XLogApiSetup {
  static var codec: FlutterStandardMessageCodec { MarsLoggingPigeonCodec.shared }
  /// Sets up an instance of `XLogApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: XLogApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! AppenderModeApi
        let logsDirArg = args[1] as! String
        let cacheDirArg = args[2] as! String
        let cacheDaysArg = args[3] as! Int64
        let nameprefixArg = args[4] as! String
        let useConsoleArg = args[5] as! Bool
        let levelArg = args[6] as! XLogLevelApi
        do {
          try api.open(mode: modeArg, logsDir: logsDirArg, cacheDir: cacheDirArg, cacheDays: cacheDaysArg, nameprefix: nameprefixArg, useConsole: useConsoleArg, level: levelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let flushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.flush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isSyncArg = args[0] as! Bool
        do {
          try api.flush(isSync: isSyncArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      flushChannel.setMessageHandler(nil)
    }
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { _, reply in
        do {
          try api.close()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
    let verboseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.verbose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      verboseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.verbose(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      verboseChannel.setMessageHandler(nil)
    }
    let debugChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.debug\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.debug(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      debugChannel.setMessageHandler(nil)
    }
    let infoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.info\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      infoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.info(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      infoChannel.setMessageHandler(nil)
    }
    let warningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.warning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      warningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.warning(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      warningChannel.setMessageHandler(nil)
    }
    let errorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.error\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      errorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.error(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      errorChannel.setMessageHandler(nil)
    }
    let fatalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mars_logging.XLogApi.fatal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fatalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        let messageArg = args[1] as! String
        do {
          try api.fatal(tag: tagArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fatalChannel.setMessageHandler(nil)
    }
  }
}
