// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.hebei.mars_logging

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is MarsLoggingError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class MarsLoggingError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class AppenderModeApi(val raw: Int) {
  ASYNC(0),
  SYNC(1);

  companion object {
    fun ofRaw(raw: Int): AppenderModeApi? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class XLogLevelApi(val raw: Int) {
  ALL(0),
  VERBOSE(1),
  DEBUG(2),
  INFO(3),
  WARNING(4),
  ERROR(5),
  FATAL(6),
  NONE(7);

  companion object {
    fun ofRaw(raw: Int): XLogLevelApi? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class MarsLoggingPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AppenderModeApi.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          XLogLevelApi.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AppenderModeApi -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is XLogLevelApi -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface XLogApi {
  fun open(mode: AppenderModeApi, logsDir: String, cacheDir: String, cacheDays: Long, nameprefix: String, useConsole: Boolean, level: XLogLevelApi)
  fun flush(isSync: Boolean)
  fun close()
  fun verbose(tag: String, message: String)
  fun debug(tag: String, message: String)
  fun info(tag: String, message: String)
  fun warning(tag: String, message: String)
  fun error(tag: String, message: String)
  fun fatal(tag: String, message: String)

  companion object {
    /** The codec used by XLogApi. */
    val codec: MessageCodec<Any?> by lazy {
      MarsLoggingPigeonCodec()
    }
    /** Sets up an instance of `XLogApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: XLogApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as AppenderModeApi
            val logsDirArg = args[1] as String
            val cacheDirArg = args[2] as String
            val cacheDaysArg = args[3] as Long
            val nameprefixArg = args[4] as String
            val useConsoleArg = args[5] as Boolean
            val levelArg = args[6] as XLogLevelApi
            val wrapped: List<Any?> = try {
              api.open(modeArg, logsDirArg, cacheDirArg, cacheDaysArg, nameprefixArg, useConsoleArg, levelArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isSyncArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.flush(isSyncArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.close()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.verbose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.verbose(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.debug$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.debug(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.info$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.info(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.warning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.warning(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.error$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.error(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging.XLogApi.fatal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.fatal(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
