// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.zeekr.mars_logging_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MarsLoggingApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is MarsLoggingError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class MarsLoggingError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class AppenderModeApi(val raw: Int) {
  ASYNC(0),
  SYNC(1);

  companion object {
    fun ofRaw(raw: Int): AppenderModeApi? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class XLogLevelApi(val raw: Int) {
  ALL(0),
  VERBOSE(1),
  DEBUG(2),
  INFO(3),
  WARNING(4),
  ERROR(5),
  FATAL(6),
  NONE(7);

  companion object {
    fun ofRaw(raw: Int): XLogLevelApi? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CompressModeApi(val raw: Int) {
  ZLIB(0),
  ZSTD(1);

  companion object {
    fun ofRaw(raw: Int): CompressModeApi? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CompressLevelApi(val raw: Int) {
  LEVEL1(0),
  LEVEL2(1),
  LEVEL3(2),
  LEVEL4(3),
  LEVEL5(4),
  LEVEL6(5),
  LEVEL7(6),
  LEVEL8(7),
  LEVEL9(8);

  companion object {
    fun ofRaw(raw: Int): CompressLevelApi? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class MarsLoggingApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AppenderModeApi.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          XLogLevelApi.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CompressModeApi.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CompressLevelApi.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AppenderModeApi -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is XLogLevelApi -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is CompressModeApi -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is CompressLevelApi -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface XLogHostApi {
  fun open(mode: AppenderModeApi, level: XLogLevelApi, logsDir: String, cacheDir: String, cacheDays: Long, namePrefix: String, compressMode: CompressModeApi, compressLevel: CompressLevelApi, pubKey: String, useConsole: Boolean, maxFileSize: Long, maxAliveDuration: Long)
  fun flush(isSync: Boolean)
  fun close()
  fun verbose(tag: String, message: String)
  fun debug(tag: String, message: String)
  fun info(tag: String, message: String)
  fun warning(tag: String, message: String)
  fun error(tag: String, message: String)
  fun fatal(tag: String, message: String)

  companion object {
    /** The codec used by XLogHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MarsLoggingApiPigeonCodec()
    }
    /** Sets up an instance of `XLogHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: XLogHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as AppenderModeApi
            val levelArg = args[1] as XLogLevelApi
            val logsDirArg = args[2] as String
            val cacheDirArg = args[3] as String
            val cacheDaysArg = args[4] as Long
            val namePrefixArg = args[5] as String
            val compressModeArg = args[6] as CompressModeApi
            val compressLevelArg = args[7] as CompressLevelApi
            val pubKeyArg = args[8] as String
            val useConsoleArg = args[9] as Boolean
            val maxFileSizeArg = args[10] as Long
            val maxAliveDurationArg = args[11] as Long
            val wrapped: List<Any?> = try {
              api.open(modeArg, levelArg, logsDirArg, cacheDirArg, cacheDaysArg, namePrefixArg, compressModeArg, compressLevelArg, pubKeyArg, useConsoleArg, maxFileSizeArg, maxAliveDurationArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isSyncArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.flush(isSyncArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.close()
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.verbose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.verbose(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.debug$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.debug(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.info$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.info(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.warning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.warning(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.error$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.error(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mars_logging_android.XLogHostApi.fatal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.fatal(tagArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MarsLoggingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
