// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as _$core;

import 'package:jni/_internal.dart' as _$jni;
import 'package:jni/jni.dart' as _$jni;

import '../../../../android/content/Context.dart' as context_;

/// from: `com.tencent.mars.xlog.Log$LogImp`
class Log_LogImp extends _$jni.JObject {
  @_$jni.internal
  @_$core.override
  final _$jni.JObjType<Log_LogImp> $type;

  @_$jni.internal
  Log_LogImp.fromReference(
    _$jni.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      _$jni.JClass.forName(r'com/tencent/mars/xlog/Log$LogImp');

  /// The type which includes information such as the signature of this class.
  static const type = $Log_LogImp$Type();
  static final _id_logV = _class.instanceMethodId(
    r'logV',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logV = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract void logV(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logV(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logV(
            reference.pointer,
            _id_logV as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logI = _class.instanceMethodId(
    r'logI',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logI = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract void logI(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logI(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logI(
            reference.pointer,
            _id_logI as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logD = _class.instanceMethodId(
    r'logD',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logD = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract void logD(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logD(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logD(
            reference.pointer,
            _id_logD as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logW = _class.instanceMethodId(
    r'logW',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logW = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract void logW(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logW(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logW(
            reference.pointer,
            _id_logW as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logE = _class.instanceMethodId(
    r'logE',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logE = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract void logE(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logE(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logE(
            reference.pointer,
            _id_logE as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logF = _class.instanceMethodId(
    r'logF',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logF = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract void logF(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logF(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logF(
            reference.pointer,
            _id_logF as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_getLogLevel = _class.instanceMethodId(
    r'getLogLevel',
    r'(J)I',
  );

  static final _getLogLevel = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<(_$jni.Int64,)>)>>('globalEnv_CallIntMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int)>();

  /// from: `public abstract int getLogLevel(long j)`
  int getLogLevel(
    int j,
  ) {
    return _getLogLevel(
            reference.pointer, _id_getLogLevel as _$jni.JMethodIDPtr, j)
        .integer;
  }

  static final _id_setAppenderMode = _class.instanceMethodId(
    r'setAppenderMode',
    r'(JI)V',
  );

  static final _setAppenderMode = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public abstract void setAppenderMode(long j, int i)`
  void setAppenderMode(
    int j,
    int i,
  ) {
    _setAppenderMode(
            reference.pointer, _id_setAppenderMode as _$jni.JMethodIDPtr, j, i)
        .check();
  }

  static final _id_openLogInstance = _class.instanceMethodId(
    r'openLogInstance',
    r'(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)J',
  );

  static final _openLogInstance = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32
                      )>)>>('globalEnv_CallLongMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int)>();

  /// from: `public abstract long openLogInstance(int i, int i1, java.lang.String string, java.lang.String string1, java.lang.String string2, int i2)`
  int openLogInstance(
    int i,
    int i1,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i2,
  ) {
    return _openLogInstance(
            reference.pointer,
            _id_openLogInstance as _$jni.JMethodIDPtr,
            i,
            i1,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i2)
        .long;
  }

  static final _id_getXlogInstance = _class.instanceMethodId(
    r'getXlogInstance',
    r'(Ljava/lang/String;)J',
  );

  static final _getXlogInstance = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JniResult Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallLongMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract long getXlogInstance(java.lang.String string)`
  int getXlogInstance(
    _$jni.JString string,
  ) {
    return _getXlogInstance(reference.pointer,
            _id_getXlogInstance as _$jni.JMethodIDPtr, string.reference.pointer)
        .long;
  }

  static final _id_releaseXlogInstance = _class.instanceMethodId(
    r'releaseXlogInstance',
    r'(Ljava/lang/String;)V',
  );

  static final _releaseXlogInstance = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public abstract void releaseXlogInstance(java.lang.String string)`
  void releaseXlogInstance(
    _$jni.JString string,
  ) {
    _releaseXlogInstance(
            reference.pointer,
            _id_releaseXlogInstance as _$jni.JMethodIDPtr,
            string.reference.pointer)
        .check();
  }

  static final _id_appenderOpen = _class.instanceMethodId(
    r'appenderOpen',
    r'(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V',
  );

  static final _appenderOpen = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int)>();

  /// from: `public abstract void appenderOpen(int i, int i1, java.lang.String string, java.lang.String string1, java.lang.String string2, int i2)`
  void appenderOpen(
    int i,
    int i1,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i2,
  ) {
    _appenderOpen(
            reference.pointer,
            _id_appenderOpen as _$jni.JMethodIDPtr,
            i,
            i1,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i2)
        .check();
  }

  static final _id_appenderClose = _class.instanceMethodId(
    r'appenderClose',
    r'()V',
  );

  static final _appenderClose = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public abstract void appenderClose()`
  void appenderClose() {
    _appenderClose(reference.pointer, _id_appenderClose as _$jni.JMethodIDPtr)
        .check();
  }

  static final _id_appenderFlush = _class.instanceMethodId(
    r'appenderFlush',
    r'(JZ)V',
  );

  static final _appenderFlush = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public abstract void appenderFlush(long j, boolean z)`
  void appenderFlush(
    int j,
    bool z,
  ) {
    _appenderFlush(reference.pointer, _id_appenderFlush as _$jni.JMethodIDPtr,
            j, z ? 1 : 0)
        .check();
  }

  static final _id_setConsoleLogOpen = _class.instanceMethodId(
    r'setConsoleLogOpen',
    r'(JZ)V',
  );

  static final _setConsoleLogOpen = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public abstract void setConsoleLogOpen(long j, boolean z)`
  void setConsoleLogOpen(
    int j,
    bool z,
  ) {
    _setConsoleLogOpen(reference.pointer,
            _id_setConsoleLogOpen as _$jni.JMethodIDPtr, j, z ? 1 : 0)
        .check();
  }

  static final _id_setMaxFileSize = _class.instanceMethodId(
    r'setMaxFileSize',
    r'(JJ)V',
  );

  static final _setMaxFileSize = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int64)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public abstract void setMaxFileSize(long j, long j1)`
  void setMaxFileSize(
    int j,
    int j1,
  ) {
    _setMaxFileSize(
            reference.pointer, _id_setMaxFileSize as _$jni.JMethodIDPtr, j, j1)
        .check();
  }

  static final _id_setMaxAliveTime = _class.instanceMethodId(
    r'setMaxAliveTime',
    r'(JJ)V',
  );

  static final _setMaxAliveTime = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int64)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public abstract void setMaxAliveTime(long j, long j1)`
  void setMaxAliveTime(
    int j,
    int j1,
  ) {
    _setMaxAliveTime(
            reference.pointer, _id_setMaxAliveTime as _$jni.JMethodIDPtr, j, j1)
        .check();
  }

  /// Maps a specific port to the implemented interface.
  static final _$core.Map<int, $Log_LogImp> _$impls = {};
  static _$jni.JObjectPtr _$invoke(
    int port,
    _$jni.JObjectPtr descriptor,
    _$jni.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      _$jni.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final _$jni.Pointer<
          _$jni.NativeFunction<
              _$jni.JObjectPtr Function(
                  _$jni.Int64, _$jni.JObjectPtr, _$jni.JObjectPtr)>>
      _$invokePointer = _$jni.Pointer.fromFunction(_$invoke);

  static _$jni.Pointer<_$jni.Void> _$invokeMethod(
    int $p,
    _$jni.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d ==
          r'logV(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V') {
        _$impls[$p]!.logV(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[6]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[7]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[8].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d ==
          r'logI(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V') {
        _$impls[$p]!.logI(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[6]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[7]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[8].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d ==
          r'logD(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V') {
        _$impls[$p]!.logD(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[6]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[7]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[8].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d ==
          r'logW(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V') {
        _$impls[$p]!.logW(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[6]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[7]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[8].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d ==
          r'logE(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V') {
        _$impls[$p]!.logE(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[6]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[7]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[8].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d ==
          r'logF(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V') {
        _$impls[$p]!.logF(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[6]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[7]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[8].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d == r'getLogLevel(J)I') {
        final $r = _$impls[$p]!.getLogLevel(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
        );
        return _$jni.JInteger($r).reference.toPointer();
      }
      if ($d == r'setAppenderMode(JI)V') {
        _$impls[$p]!.setAppenderMode(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d ==
          r'openLogInstance(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)J') {
        final $r = _$impls[$p]!.openLogInstance(
          $a[0]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[1]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
        );
        return _$jni.JLong($r).reference.toPointer();
      }
      if ($d == r'getXlogInstance(Ljava/lang/String;)J') {
        final $r = _$impls[$p]!.getXlogInstance(
          $a[0].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.JLong($r).reference.toPointer();
      }
      if ($d == r'releaseXlogInstance(Ljava/lang/String;)V') {
        _$impls[$p]!.releaseXlogInstance(
          $a[0].as(const _$jni.JStringType(), releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d ==
          r'appenderOpen(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V') {
        _$impls[$p]!.appenderOpen(
          $a[0]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[1]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
          $a[2].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[3].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[4].as(const _$jni.JStringType(), releaseOriginal: true),
          $a[5]
              .as(const _$jni.JIntegerType(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d == r'appenderClose()V') {
        _$impls[$p]!.appenderClose();
        return _$jni.nullptr;
      }
      if ($d == r'appenderFlush(JZ)V') {
        _$impls[$p]!.appenderFlush(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1]
              .as(const _$jni.JBooleanType(), releaseOriginal: true)
              .booleanValue(releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d == r'setConsoleLogOpen(JZ)V') {
        _$impls[$p]!.setConsoleLogOpen(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1]
              .as(const _$jni.JBooleanType(), releaseOriginal: true)
              .booleanValue(releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d == r'setMaxFileSize(JJ)V') {
        _$impls[$p]!.setMaxFileSize(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
      if ($d == r'setMaxAliveTime(JJ)V') {
        _$impls[$p]!.setMaxAliveTime(
          $a[0]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
          $a[1]
              .as(const _$jni.JLongType(), releaseOriginal: true)
              .longValue(releaseOriginal: true),
        );
        return _$jni.nullptr;
      }
    } catch (e) {
      return _$jni.ProtectedJniExtensions.newDartException(e);
    }
    return _$jni.nullptr;
  }

  static void implementIn(
    _$jni.JImplementer implementer,
    $Log_LogImp $impl,
  ) {
    late final _$jni.RawReceivePort $p;
    $p = _$jni.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = _$jni.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      _$jni.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.tencent.mars.xlog.Log$LogImp',
      $p,
      _$invokePointer,
      [
        if ($impl.logV$async)
          r'logV(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
        if ($impl.logI$async)
          r'logI(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
        if ($impl.logD$async)
          r'logD(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
        if ($impl.logW$async)
          r'logW(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
        if ($impl.logE$async)
          r'logE(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
        if ($impl.logF$async)
          r'logF(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
        if ($impl.setAppenderMode$async) r'setAppenderMode(JI)V',
        if ($impl.releaseXlogInstance$async)
          r'releaseXlogInstance(Ljava/lang/String;)V',
        if ($impl.appenderOpen$async)
          r'appenderOpen(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V',
        if ($impl.appenderClose$async) r'appenderClose()V',
        if ($impl.appenderFlush$async) r'appenderFlush(JZ)V',
        if ($impl.setConsoleLogOpen$async) r'setConsoleLogOpen(JZ)V',
        if ($impl.setMaxFileSize$async) r'setMaxFileSize(JJ)V',
        if ($impl.setMaxAliveTime$async) r'setMaxAliveTime(JJ)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory Log_LogImp.implement(
    $Log_LogImp $impl,
  ) {
    final $i = _$jni.JImplementer();
    implementIn($i, $impl);
    return Log_LogImp.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $Log_LogImp {
  factory $Log_LogImp({
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logV,
    bool logV$async,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logI,
    bool logI$async,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logD,
    bool logD$async,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logW,
    bool logW$async,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logE,
    bool logE$async,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logF,
    bool logF$async,
    required int Function(int j) getLogLevel,
    required void Function(int j, int i) setAppenderMode,
    bool setAppenderMode$async,
    required int Function(int i, int i1, _$jni.JString string,
            _$jni.JString string1, _$jni.JString string2, int i2)
        openLogInstance,
    required int Function(_$jni.JString string) getXlogInstance,
    required void Function(_$jni.JString string) releaseXlogInstance,
    bool releaseXlogInstance$async,
    required void Function(int i, int i1, _$jni.JString string,
            _$jni.JString string1, _$jni.JString string2, int i2)
        appenderOpen,
    bool appenderOpen$async,
    required void Function() appenderClose,
    bool appenderClose$async,
    required void Function(int j, bool z) appenderFlush,
    bool appenderFlush$async,
    required void Function(int j, bool z) setConsoleLogOpen,
    bool setConsoleLogOpen$async,
    required void Function(int j, int j1) setMaxFileSize,
    bool setMaxFileSize$async,
    required void Function(int j, int j1) setMaxAliveTime,
    bool setMaxAliveTime$async,
  }) = _$Log_LogImp;

  void logV(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3);
  bool get logV$async => false;
  void logI(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3);
  bool get logI$async => false;
  void logD(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3);
  bool get logD$async => false;
  void logW(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3);
  bool get logW$async => false;
  void logE(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3);
  bool get logE$async => false;
  void logF(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3);
  bool get logF$async => false;
  int getLogLevel(int j);
  void setAppenderMode(int j, int i);
  bool get setAppenderMode$async => false;
  int openLogInstance(int i, int i1, _$jni.JString string,
      _$jni.JString string1, _$jni.JString string2, int i2);
  int getXlogInstance(_$jni.JString string);
  void releaseXlogInstance(_$jni.JString string);
  bool get releaseXlogInstance$async => false;
  void appenderOpen(int i, int i1, _$jni.JString string, _$jni.JString string1,
      _$jni.JString string2, int i2);
  bool get appenderOpen$async => false;
  void appenderClose();
  bool get appenderClose$async => false;
  void appenderFlush(int j, bool z);
  bool get appenderFlush$async => false;
  void setConsoleLogOpen(int j, bool z);
  bool get setConsoleLogOpen$async => false;
  void setMaxFileSize(int j, int j1);
  bool get setMaxFileSize$async => false;
  void setMaxAliveTime(int j, int j1);
  bool get setMaxAliveTime$async => false;
}

final class _$Log_LogImp with $Log_LogImp {
  _$Log_LogImp({
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logV,
    this.logV$async = false,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logI,
    this.logI$async = false,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logD,
    this.logD$async = false,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logW,
    this.logW$async = false,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logE,
    this.logE$async = false,
    required void Function(
            int j,
            _$jni.JString string,
            _$jni.JString string1,
            _$jni.JString string2,
            int i,
            int i1,
            int j1,
            int j2,
            _$jni.JString string3)
        logF,
    this.logF$async = false,
    required int Function(int j) getLogLevel,
    required void Function(int j, int i) setAppenderMode,
    this.setAppenderMode$async = false,
    required int Function(int i, int i1, _$jni.JString string,
            _$jni.JString string1, _$jni.JString string2, int i2)
        openLogInstance,
    required int Function(_$jni.JString string) getXlogInstance,
    required void Function(_$jni.JString string) releaseXlogInstance,
    this.releaseXlogInstance$async = false,
    required void Function(int i, int i1, _$jni.JString string,
            _$jni.JString string1, _$jni.JString string2, int i2)
        appenderOpen,
    this.appenderOpen$async = false,
    required void Function() appenderClose,
    this.appenderClose$async = false,
    required void Function(int j, bool z) appenderFlush,
    this.appenderFlush$async = false,
    required void Function(int j, bool z) setConsoleLogOpen,
    this.setConsoleLogOpen$async = false,
    required void Function(int j, int j1) setMaxFileSize,
    this.setMaxFileSize$async = false,
    required void Function(int j, int j1) setMaxAliveTime,
    this.setMaxAliveTime$async = false,
  })  : _logV = logV,
        _logI = logI,
        _logD = logD,
        _logW = logW,
        _logE = logE,
        _logF = logF,
        _getLogLevel = getLogLevel,
        _setAppenderMode = setAppenderMode,
        _openLogInstance = openLogInstance,
        _getXlogInstance = getXlogInstance,
        _releaseXlogInstance = releaseXlogInstance,
        _appenderOpen = appenderOpen,
        _appenderClose = appenderClose,
        _appenderFlush = appenderFlush,
        _setConsoleLogOpen = setConsoleLogOpen,
        _setMaxFileSize = setMaxFileSize,
        _setMaxAliveTime = setMaxAliveTime;

  final void Function(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) _logV;
  final bool logV$async;
  final void Function(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) _logI;
  final bool logI$async;
  final void Function(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) _logD;
  final bool logD$async;
  final void Function(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) _logW;
  final bool logW$async;
  final void Function(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) _logE;
  final bool logE$async;
  final void Function(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) _logF;
  final bool logF$async;
  final int Function(int j) _getLogLevel;
  final void Function(int j, int i) _setAppenderMode;
  final bool setAppenderMode$async;
  final int Function(int i, int i1, _$jni.JString string, _$jni.JString string1,
      _$jni.JString string2, int i2) _openLogInstance;
  final int Function(_$jni.JString string) _getXlogInstance;
  final void Function(_$jni.JString string) _releaseXlogInstance;
  final bool releaseXlogInstance$async;
  final void Function(int i, int i1, _$jni.JString string,
      _$jni.JString string1, _$jni.JString string2, int i2) _appenderOpen;
  final bool appenderOpen$async;
  final void Function() _appenderClose;
  final bool appenderClose$async;
  final void Function(int j, bool z) _appenderFlush;
  final bool appenderFlush$async;
  final void Function(int j, bool z) _setConsoleLogOpen;
  final bool setConsoleLogOpen$async;
  final void Function(int j, int j1) _setMaxFileSize;
  final bool setMaxFileSize$async;
  final void Function(int j, int j1) _setMaxAliveTime;
  final bool setMaxAliveTime$async;

  void logV(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) {
    return _logV(j, string, string1, string2, i, i1, j1, j2, string3);
  }

  void logI(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) {
    return _logI(j, string, string1, string2, i, i1, j1, j2, string3);
  }

  void logD(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) {
    return _logD(j, string, string1, string2, i, i1, j1, j2, string3);
  }

  void logW(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) {
    return _logW(j, string, string1, string2, i, i1, j1, j2, string3);
  }

  void logE(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) {
    return _logE(j, string, string1, string2, i, i1, j1, j2, string3);
  }

  void logF(
      int j,
      _$jni.JString string,
      _$jni.JString string1,
      _$jni.JString string2,
      int i,
      int i1,
      int j1,
      int j2,
      _$jni.JString string3) {
    return _logF(j, string, string1, string2, i, i1, j1, j2, string3);
  }

  int getLogLevel(int j) {
    return _getLogLevel(j);
  }

  void setAppenderMode(int j, int i) {
    return _setAppenderMode(j, i);
  }

  int openLogInstance(int i, int i1, _$jni.JString string,
      _$jni.JString string1, _$jni.JString string2, int i2) {
    return _openLogInstance(i, i1, string, string1, string2, i2);
  }

  int getXlogInstance(_$jni.JString string) {
    return _getXlogInstance(string);
  }

  void releaseXlogInstance(_$jni.JString string) {
    return _releaseXlogInstance(string);
  }

  void appenderOpen(int i, int i1, _$jni.JString string, _$jni.JString string1,
      _$jni.JString string2, int i2) {
    return _appenderOpen(i, i1, string, string1, string2, i2);
  }

  void appenderClose() {
    return _appenderClose();
  }

  void appenderFlush(int j, bool z) {
    return _appenderFlush(j, z);
  }

  void setConsoleLogOpen(int j, bool z) {
    return _setConsoleLogOpen(j, z);
  }

  void setMaxFileSize(int j, int j1) {
    return _setMaxFileSize(j, j1);
  }

  void setMaxAliveTime(int j, int j1) {
    return _setMaxAliveTime(j, j1);
  }
}

final class $Log_LogImp$Type extends _$jni.JObjType<Log_LogImp> {
  @_$jni.internal
  const $Log_LogImp$Type();

  @_$jni.internal
  @_$core.override
  String get signature => r'Lcom/tencent/mars/xlog/Log$LogImp;';

  @_$jni.internal
  @_$core.override
  Log_LogImp fromReference(_$jni.JReference reference) =>
      Log_LogImp.fromReference(reference);

  @_$jni.internal
  @_$core.override
  _$jni.JObjType get superType => const _$jni.JObjectType();

  @_$jni.internal
  @_$core.override
  final superCount = 1;

  @_$core.override
  int get hashCode => ($Log_LogImp$Type).hashCode;

  @_$core.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Log_LogImp$Type) && other is $Log_LogImp$Type;
  }
}

/// from: `com.tencent.mars.xlog.Log$LogInstance`
class Log_LogInstance extends _$jni.JObject {
  @_$jni.internal
  @_$core.override
  final _$jni.JObjType<Log_LogInstance> $type;

  @_$jni.internal
  Log_LogInstance.fromReference(
    _$jni.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      _$jni.JClass.forName(r'com/tencent/mars/xlog/Log$LogInstance');

  /// The type which includes information such as the signature of this class.
  static const type = $Log_LogInstance$Type();
  static final _id_f = _class.instanceMethodId(
    r'f',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _f = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void f(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  void f(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _f(reference.pointer, _id_f as _$jni.JMethodIDPtr, string.reference.pointer,
            string1.reference.pointer, objects.reference.pointer)
        .check();
  }

  static final _id_e = _class.instanceMethodId(
    r'e',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _e = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void e(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  void e(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _e(reference.pointer, _id_e as _$jni.JMethodIDPtr, string.reference.pointer,
            string1.reference.pointer, objects.reference.pointer)
        .check();
  }

  static final _id_w = _class.instanceMethodId(
    r'w',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _w = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void w(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  void w(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _w(reference.pointer, _id_w as _$jni.JMethodIDPtr, string.reference.pointer,
            string1.reference.pointer, objects.reference.pointer)
        .check();
  }

  static final _id_i = _class.instanceMethodId(
    r'i',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _i = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void i(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  void i(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _i(reference.pointer, _id_i as _$jni.JMethodIDPtr, string.reference.pointer,
            string1.reference.pointer, objects.reference.pointer)
        .check();
  }

  static final _id_d = _class.instanceMethodId(
    r'd',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _d = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void d(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  void d(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _d(reference.pointer, _id_d as _$jni.JMethodIDPtr, string.reference.pointer,
            string1.reference.pointer, objects.reference.pointer)
        .check();
  }

  static final _id_v = _class.instanceMethodId(
    r'v',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _v = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void v(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  void v(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _v(reference.pointer, _id_v as _$jni.JMethodIDPtr, string.reference.pointer,
            string1.reference.pointer, objects.reference.pointer)
        .check();
  }

  static final _id_printErrStackTrace = _class.instanceMethodId(
    r'printErrStackTrace',
    r'(Ljava/lang/String;Ljava/lang/Throwable;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _printErrStackTrace = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void printErrStackTrace(java.lang.String string, java.lang.Throwable throwable, java.lang.String string1, java.lang.Object[] objects)`
  void printErrStackTrace(
    _$jni.JString string,
    _$jni.JObject throwable,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _printErrStackTrace(
            reference.pointer,
            _id_printErrStackTrace as _$jni.JMethodIDPtr,
            string.reference.pointer,
            throwable.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_appenderFlush = _class.instanceMethodId(
    r'appenderFlush',
    r'()V',
  );

  static final _appenderFlush = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void appenderFlush()`
  void appenderFlush() {
    _appenderFlush(reference.pointer, _id_appenderFlush as _$jni.JMethodIDPtr)
        .check();
  }

  static final _id_appenderFlushSync = _class.instanceMethodId(
    r'appenderFlushSync',
    r'()V',
  );

  static final _appenderFlushSync = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void appenderFlushSync()`
  void appenderFlushSync() {
    _appenderFlushSync(
            reference.pointer, _id_appenderFlushSync as _$jni.JMethodIDPtr)
        .check();
  }

  static final _id_getLogLevel = _class.instanceMethodId(
    r'getLogLevel',
    r'()I',
  );

  static final _getLogLevel = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallIntMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public int getLogLevel()`
  int getLogLevel() {
    return _getLogLevel(
            reference.pointer, _id_getLogLevel as _$jni.JMethodIDPtr)
        .integer;
  }

  static final _id_setConsoleLogOpen = _class.instanceMethodId(
    r'setConsoleLogOpen',
    r'(Z)V',
  );

  static final _setConsoleLogOpen = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<(_$jni.Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int)>();

  /// from: `public void setConsoleLogOpen(boolean z)`
  void setConsoleLogOpen(
    bool z,
  ) {
    _setConsoleLogOpen(reference.pointer,
            _id_setConsoleLogOpen as _$jni.JMethodIDPtr, z ? 1 : 0)
        .check();
  }
}

final class $Log_LogInstance$Type extends _$jni.JObjType<Log_LogInstance> {
  @_$jni.internal
  const $Log_LogInstance$Type();

  @_$jni.internal
  @_$core.override
  String get signature => r'Lcom/tencent/mars/xlog/Log$LogInstance;';

  @_$jni.internal
  @_$core.override
  Log_LogInstance fromReference(_$jni.JReference reference) =>
      Log_LogInstance.fromReference(reference);

  @_$jni.internal
  @_$core.override
  _$jni.JObjType get superType => const _$jni.JObjectType();

  @_$jni.internal
  @_$core.override
  final superCount = 1;

  @_$core.override
  int get hashCode => ($Log_LogInstance$Type).hashCode;

  @_$core.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Log_LogInstance$Type) &&
        other is $Log_LogInstance$Type;
  }
}

/// from: `com.tencent.mars.xlog.Log`
class Log extends _$jni.JObject {
  @_$jni.internal
  @_$core.override
  final _$jni.JObjType<Log> $type;

  @_$jni.internal
  Log.fromReference(
    _$jni.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = _$jni.JClass.forName(r'com/tencent/mars/xlog/Log');

  /// The type which includes information such as the signature of this class.
  static const type = $Log$Type();

  /// from: `static public final int LEVEL_VERBOSE`
  static const LEVEL_VERBOSE = 0;

  /// from: `static public final int LEVEL_DEBUG`
  static const LEVEL_DEBUG = 1;

  /// from: `static public final int LEVEL_INFO`
  static const LEVEL_INFO = 2;

  /// from: `static public final int LEVEL_WARNING`
  static const LEVEL_WARNING = 3;

  /// from: `static public final int LEVEL_ERROR`
  static const LEVEL_ERROR = 4;

  /// from: `static public final int LEVEL_FATAL`
  static const LEVEL_FATAL = 5;

  /// from: `static public final int LEVEL_NONE`
  static const LEVEL_NONE = 6;
  static final _id_toastSupportContext = _class.staticFieldId(
    r'toastSupportContext',
    r'Landroid/content/Context;',
  );

  /// from: `static public android.content.Context toastSupportContext`
  /// The returned object must be released after use, by calling the [release] method.
  static context_.Context get toastSupportContext =>
      _id_toastSupportContext.get(_class, const context_.$Context$Type());

  /// from: `static public android.content.Context toastSupportContext`
  /// The returned object must be released after use, by calling the [release] method.
  static set toastSupportContext(context_.Context value) =>
      _id_toastSupportContext.set(
          _class, const context_.$Context$Type(), value);

  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Log() {
    return Log.fromReference(
        _new$(_class.reference.pointer, _id_new$ as _$jni.JMethodIDPtr)
            .reference);
  }

  static final _id_setLogImp = _class.staticMethodId(
    r'setLogImp',
    r'(Lcom/tencent/mars/xlog/Log$LogImp;)V',
  );

  static final _setLogImp = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void setLogImp(com.tencent.mars.xlog.Log$LogImp logImp)`
  static void setLogImp(
    Log_LogImp logImp,
  ) {
    _setLogImp(_class.reference.pointer, _id_setLogImp as _$jni.JMethodIDPtr,
            logImp.reference.pointer)
        .check();
  }

  static final _id_getImpl = _class.staticMethodId(
    r'getImpl',
    r'()Lcom/tencent/mars/xlog/Log$LogImp;',
  );

  static final _getImpl = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `static public com.tencent.mars.xlog.Log$LogImp getImpl()`
  /// The returned object must be released after use, by calling the [release] method.
  static Log_LogImp getImpl() {
    return _getImpl(_class.reference.pointer, _id_getImpl as _$jni.JMethodIDPtr)
        .object(const $Log_LogImp$Type());
  }

  static final _id_appenderOpen = _class.staticMethodId(
    r'appenderOpen',
    r'(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V',
  );

  static final _appenderOpen = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int)>();

  /// from: `static public void appenderOpen(int i, int i1, java.lang.String string, java.lang.String string1, java.lang.String string2, int i2)`
  static void appenderOpen(
    int i,
    int i1,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i2,
  ) {
    _appenderOpen(
            _class.reference.pointer,
            _id_appenderOpen as _$jni.JMethodIDPtr,
            i,
            i1,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i2)
        .check();
  }

  static final _id_appenderClose = _class.staticMethodId(
    r'appenderClose',
    r'()V',
  );

  static final _appenderClose = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `static public void appenderClose()`
  static void appenderClose() {
    _appenderClose(
            _class.reference.pointer, _id_appenderClose as _$jni.JMethodIDPtr)
        .check();
  }

  static final _id_appenderFlush = _class.staticMethodId(
    r'appenderFlush',
    r'()V',
  );

  static final _appenderFlush = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `static public void appenderFlush()`
  static void appenderFlush() {
    _appenderFlush(
            _class.reference.pointer, _id_appenderFlush as _$jni.JMethodIDPtr)
        .check();
  }

  static final _id_appenderFlushSync = _class.staticMethodId(
    r'appenderFlushSync',
    r'(Z)V',
  );

  static final _appenderFlushSync = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr, _$jni.VarArgs<(_$jni.Int32,)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int)>();

  /// from: `static public void appenderFlushSync(boolean z)`
  static void appenderFlushSync(
    bool z,
  ) {
    _appenderFlushSync(_class.reference.pointer,
            _id_appenderFlushSync as _$jni.JMethodIDPtr, z ? 1 : 0)
        .check();
  }

  static final _id_getLogLevel = _class.staticMethodId(
    r'getLogLevel',
    r'()I',
  );

  static final _getLogLevel = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallStaticIntMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `static public int getLogLevel()`
  static int getLogLevel() {
    return _getLogLevel(
            _class.reference.pointer, _id_getLogLevel as _$jni.JMethodIDPtr)
        .integer;
  }

  static final _id_setLevel = _class.staticMethodId(
    r'setLevel',
    r'(IZ)V',
  );

  static final _setLevel = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int32, _$jni.Int32)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `static public void setLevel(int i, boolean z)`
  static void setLevel(
    int i,
    bool z,
  ) {
    _setLevel(_class.reference.pointer, _id_setLevel as _$jni.JMethodIDPtr, i,
            z ? 1 : 0)
        .check();
  }

  static final _id_setConsoleLogOpen = _class.staticMethodId(
    r'setConsoleLogOpen',
    r'(Z)V',
  );

  static final _setConsoleLogOpen = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr, _$jni.VarArgs<(_$jni.Int32,)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int)>();

  /// from: `static public void setConsoleLogOpen(boolean z)`
  static void setConsoleLogOpen(
    bool z,
  ) {
    _setConsoleLogOpen(_class.reference.pointer,
            _id_setConsoleLogOpen as _$jni.JMethodIDPtr, z ? 1 : 0)
        .check();
  }

  static final _id_f = _class.staticMethodId(
    r'f',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _f = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void f(java.lang.String string, java.lang.String string1)`
  static void f(
    _$jni.JString string,
    _$jni.JString string1,
  ) {
    _f(_class.reference.pointer, _id_f as _$jni.JMethodIDPtr,
            string.reference.pointer, string1.reference.pointer)
        .check();
  }

  static final _id_e = _class.staticMethodId(
    r'e',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _e = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void e(java.lang.String string, java.lang.String string1)`
  static void e(
    _$jni.JString string,
    _$jni.JString string1,
  ) {
    _e(_class.reference.pointer, _id_e as _$jni.JMethodIDPtr,
            string.reference.pointer, string1.reference.pointer)
        .check();
  }

  static final _id_w = _class.staticMethodId(
    r'w',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _w = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void w(java.lang.String string, java.lang.String string1)`
  static void w(
    _$jni.JString string,
    _$jni.JString string1,
  ) {
    _w(_class.reference.pointer, _id_w as _$jni.JMethodIDPtr,
            string.reference.pointer, string1.reference.pointer)
        .check();
  }

  static final _id_i = _class.staticMethodId(
    r'i',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _i = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void i(java.lang.String string, java.lang.String string1)`
  static void i(
    _$jni.JString string,
    _$jni.JString string1,
  ) {
    _i(_class.reference.pointer, _id_i as _$jni.JMethodIDPtr,
            string.reference.pointer, string1.reference.pointer)
        .check();
  }

  static final _id_d = _class.staticMethodId(
    r'd',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _d = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void d(java.lang.String string, java.lang.String string1)`
  static void d(
    _$jni.JString string,
    _$jni.JString string1,
  ) {
    _d(_class.reference.pointer, _id_d as _$jni.JMethodIDPtr,
            string.reference.pointer, string1.reference.pointer)
        .check();
  }

  static final _id_v = _class.staticMethodId(
    r'v',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _v = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void v(java.lang.String string, java.lang.String string1)`
  static void v(
    _$jni.JString string,
    _$jni.JString string1,
  ) {
    _v(_class.reference.pointer, _id_v as _$jni.JMethodIDPtr,
            string.reference.pointer, string1.reference.pointer)
        .check();
  }

  static final _id_f$1 = _class.staticMethodId(
    r'f',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _f$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void f(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  static void f$1(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _f$1(
            _class.reference.pointer,
            _id_f$1 as _$jni.JMethodIDPtr,
            string.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_e$1 = _class.staticMethodId(
    r'e',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _e$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void e(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  static void e$1(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _e$1(
            _class.reference.pointer,
            _id_e$1 as _$jni.JMethodIDPtr,
            string.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_w$1 = _class.staticMethodId(
    r'w',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _w$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void w(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  static void w$1(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _w$1(
            _class.reference.pointer,
            _id_w$1 as _$jni.JMethodIDPtr,
            string.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_i$1 = _class.staticMethodId(
    r'i',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _i$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void i(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  static void i$1(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _i$1(
            _class.reference.pointer,
            _id_i$1 as _$jni.JMethodIDPtr,
            string.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_d$1 = _class.staticMethodId(
    r'd',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _d$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void d(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  static void d$1(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _d$1(
            _class.reference.pointer,
            _id_d$1 as _$jni.JMethodIDPtr,
            string.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_v$1 = _class.staticMethodId(
    r'v',
    r'(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _v$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void v(java.lang.String string, java.lang.String string1, java.lang.Object[] objects)`
  static void v$1(
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _v$1(
            _class.reference.pointer,
            _id_v$1 as _$jni.JMethodIDPtr,
            string.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_printErrStackTrace = _class.staticMethodId(
    r'printErrStackTrace',
    r'(Ljava/lang/String;Ljava/lang/Throwable;Ljava/lang/String;[Ljava/lang/Object;)V',
  );

  static final _printErrStackTrace = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void printErrStackTrace(java.lang.String string, java.lang.Throwable throwable, java.lang.String string1, java.lang.Object[] objects)`
  static void printErrStackTrace(
    _$jni.JString string,
    _$jni.JObject throwable,
    _$jni.JString string1,
    _$jni.JArray<_$jni.JObject> objects,
  ) {
    _printErrStackTrace(
            _class.reference.pointer,
            _id_printErrStackTrace as _$jni.JMethodIDPtr,
            string.reference.pointer,
            throwable.reference.pointer,
            string1.reference.pointer,
            objects.reference.pointer)
        .check();
  }

  static final _id_openLogInstance = _class.staticMethodId(
    r'openLogInstance',
    r'(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Lcom/tencent/mars/xlog/Log$LogInstance;',
  );

  static final _openLogInstance = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int)>();

  /// from: `static public com.tencent.mars.xlog.Log$LogInstance openLogInstance(int i, int i1, java.lang.String string, java.lang.String string1, java.lang.String string2, int i2)`
  /// The returned object must be released after use, by calling the [release] method.
  static Log_LogInstance openLogInstance(
    int i,
    int i1,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i2,
  ) {
    return _openLogInstance(
            _class.reference.pointer,
            _id_openLogInstance as _$jni.JMethodIDPtr,
            i,
            i1,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i2)
        .object(const $Log_LogInstance$Type());
  }

  static final _id_closeLogInstance = _class.staticMethodId(
    r'closeLogInstance',
    r'(Ljava/lang/String;)V',
  );

  static final _closeLogInstance = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void closeLogInstance(java.lang.String string)`
  static void closeLogInstance(
    _$jni.JString string,
  ) {
    _closeLogInstance(
            _class.reference.pointer,
            _id_closeLogInstance as _$jni.JMethodIDPtr,
            string.reference.pointer)
        .check();
  }

  static final _id_getLogInstance = _class.staticMethodId(
    r'getLogInstance',
    r'(Ljava/lang/String;)Lcom/tencent/mars/xlog/Log$LogInstance;',
  );

  static final _getLogInstance = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JniResult Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public com.tencent.mars.xlog.Log$LogInstance getLogInstance(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  static Log_LogInstance getLogInstance(
    _$jni.JString string,
  ) {
    return _getLogInstance(_class.reference.pointer,
            _id_getLogInstance as _$jni.JMethodIDPtr, string.reference.pointer)
        .object(const $Log_LogInstance$Type());
  }
}

final class $Log$Type extends _$jni.JObjType<Log> {
  @_$jni.internal
  const $Log$Type();

  @_$jni.internal
  @_$core.override
  String get signature => r'Lcom/tencent/mars/xlog/Log;';

  @_$jni.internal
  @_$core.override
  Log fromReference(_$jni.JReference reference) => Log.fromReference(reference);

  @_$jni.internal
  @_$core.override
  _$jni.JObjType get superType => const _$jni.JObjectType();

  @_$jni.internal
  @_$core.override
  final superCount = 1;

  @_$core.override
  int get hashCode => ($Log$Type).hashCode;

  @_$core.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Log$Type) && other is $Log$Type;
  }
}
