// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as _$core;

import 'package:jni/_internal.dart' as _$jni;
import 'package:jni/jni.dart' as _$jni;

/// from: `com.tencent.mars.xlog.Xlog$XLogConfig`
class Xlog_XLogConfig extends _$jni.JObject {
  @_$jni.internal
  @_$core.override
  final _$jni.JObjType<Xlog_XLogConfig> $type;

  @_$jni.internal
  Xlog_XLogConfig.fromReference(
    _$jni.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      _$jni.JClass.forName(r'com/tencent/mars/xlog/Xlog$XLogConfig');

  /// The type which includes information such as the signature of this class.
  static const type = $Xlog_XLogConfig$Type();
  static final _id_level = _class.instanceFieldId(
    r'level',
    r'I',
  );

  /// from: `public int level`
  int get level => _id_level.get(this, const _$jni.jintType());

  /// from: `public int level`
  set level(int value) => _id_level.set(this, const _$jni.jintType(), value);

  static final _id_mode = _class.instanceFieldId(
    r'mode',
    r'I',
  );

  /// from: `public int mode`
  int get mode => _id_mode.get(this, const _$jni.jintType());

  /// from: `public int mode`
  set mode(int value) => _id_mode.set(this, const _$jni.jintType(), value);

  static final _id_logdir = _class.instanceFieldId(
    r'logdir',
    r'Ljava/lang/String;',
  );

  /// from: `public java.lang.String logdir`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JString get logdir => _id_logdir.get(this, const _$jni.JStringType());

  /// from: `public java.lang.String logdir`
  /// The returned object must be released after use, by calling the [release] method.
  set logdir(_$jni.JString value) =>
      _id_logdir.set(this, const _$jni.JStringType(), value);

  static final _id_nameprefix = _class.instanceFieldId(
    r'nameprefix',
    r'Ljava/lang/String;',
  );

  /// from: `public java.lang.String nameprefix`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JString get nameprefix =>
      _id_nameprefix.get(this, const _$jni.JStringType());

  /// from: `public java.lang.String nameprefix`
  /// The returned object must be released after use, by calling the [release] method.
  set nameprefix(_$jni.JString value) =>
      _id_nameprefix.set(this, const _$jni.JStringType(), value);

  static final _id_pubkey = _class.instanceFieldId(
    r'pubkey',
    r'Ljava/lang/String;',
  );

  /// from: `public java.lang.String pubkey`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JString get pubkey => _id_pubkey.get(this, const _$jni.JStringType());

  /// from: `public java.lang.String pubkey`
  /// The returned object must be released after use, by calling the [release] method.
  set pubkey(_$jni.JString value) =>
      _id_pubkey.set(this, const _$jni.JStringType(), value);

  static final _id_compressmode = _class.instanceFieldId(
    r'compressmode',
    r'I',
  );

  /// from: `public int compressmode`
  int get compressmode => _id_compressmode.get(this, const _$jni.jintType());

  /// from: `public int compressmode`
  set compressmode(int value) =>
      _id_compressmode.set(this, const _$jni.jintType(), value);

  static final _id_compresslevel = _class.instanceFieldId(
    r'compresslevel',
    r'I',
  );

  /// from: `public int compresslevel`
  int get compresslevel => _id_compresslevel.get(this, const _$jni.jintType());

  /// from: `public int compresslevel`
  set compresslevel(int value) =>
      _id_compresslevel.set(this, const _$jni.jintType(), value);

  static final _id_cachedir = _class.instanceFieldId(
    r'cachedir',
    r'Ljava/lang/String;',
  );

  /// from: `public java.lang.String cachedir`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JString get cachedir =>
      _id_cachedir.get(this, const _$jni.JStringType());

  /// from: `public java.lang.String cachedir`
  /// The returned object must be released after use, by calling the [release] method.
  set cachedir(_$jni.JString value) =>
      _id_cachedir.set(this, const _$jni.JStringType(), value);

  static final _id_cachedays = _class.instanceFieldId(
    r'cachedays',
    r'I',
  );

  /// from: `public int cachedays`
  int get cachedays => _id_cachedays.get(this, const _$jni.jintType());

  /// from: `public int cachedays`
  set cachedays(int value) =>
      _id_cachedays.set(this, const _$jni.jintType(), value);

  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Xlog_XLogConfig() {
    return Xlog_XLogConfig.fromReference(
        _new$(_class.reference.pointer, _id_new$ as _$jni.JMethodIDPtr)
            .reference);
  }
}

final class $Xlog_XLogConfig$Type extends _$jni.JObjType<Xlog_XLogConfig> {
  @_$jni.internal
  const $Xlog_XLogConfig$Type();

  @_$jni.internal
  @_$core.override
  String get signature => r'Lcom/tencent/mars/xlog/Xlog$XLogConfig;';

  @_$jni.internal
  @_$core.override
  Xlog_XLogConfig fromReference(_$jni.JReference reference) =>
      Xlog_XLogConfig.fromReference(reference);

  @_$jni.internal
  @_$core.override
  _$jni.JObjType get superType => const _$jni.JObjectType();

  @_$jni.internal
  @_$core.override
  final superCount = 1;

  @_$core.override
  int get hashCode => ($Xlog_XLogConfig$Type).hashCode;

  @_$core.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Xlog_XLogConfig$Type) &&
        other is $Xlog_XLogConfig$Type;
  }
}

/// from: `com.tencent.mars.xlog.Xlog`
class Xlog extends _$jni.JObject {
  @_$jni.internal
  @_$core.override
  final _$jni.JObjType<Xlog> $type;

  @_$jni.internal
  Xlog.fromReference(
    _$jni.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = _$jni.JClass.forName(r'com/tencent/mars/xlog/Xlog');

  /// The type which includes information such as the signature of this class.
  static const type = $Xlog$Type();

  /// from: `static public final int LEVEL_ALL`
  static const LEVEL_ALL = 0;

  /// from: `static public final int LEVEL_VERBOSE`
  static const LEVEL_VERBOSE = 0;

  /// from: `static public final int LEVEL_DEBUG`
  static const LEVEL_DEBUG = 1;

  /// from: `static public final int LEVEL_INFO`
  static const LEVEL_INFO = 2;

  /// from: `static public final int LEVEL_WARNING`
  static const LEVEL_WARNING = 3;

  /// from: `static public final int LEVEL_ERROR`
  static const LEVEL_ERROR = 4;

  /// from: `static public final int LEVEL_FATAL`
  static const LEVEL_FATAL = 5;

  /// from: `static public final int LEVEL_NONE`
  static const LEVEL_NONE = 6;

  /// from: `static public final int COMPRESS_LEVEL1`
  static const COMPRESS_LEVEL1 = 1;

  /// from: `static public final int COMPRESS_LEVEL2`
  static const COMPRESS_LEVEL2 = 2;

  /// from: `static public final int COMPRESS_LEVEL3`
  static const COMPRESS_LEVEL3 = 3;

  /// from: `static public final int COMPRESS_LEVEL4`
  static const COMPRESS_LEVEL4 = 4;

  /// from: `static public final int COMPRESS_LEVEL5`
  static const COMPRESS_LEVEL5 = 5;

  /// from: `static public final int COMPRESS_LEVEL6`
  static const COMPRESS_LEVEL6 = 6;

  /// from: `static public final int COMPRESS_LEVEL7`
  static const COMPRESS_LEVEL7 = 7;

  /// from: `static public final int COMPRESS_LEVEL8`
  static const COMPRESS_LEVEL8 = 8;

  /// from: `static public final int COMPRESS_LEVEL9`
  static const COMPRESS_LEVEL9 = 9;

  /// from: `static public final int AppednerModeAsync`
  static const AppednerModeAsync = 0;

  /// from: `static public final int AppednerModeSync`
  static const AppednerModeSync = 1;

  /// from: `static public final int ZLIB_MODE`
  static const ZLIB_MODE = 0;

  /// from: `static public final int ZSTD_MODE`
  static const ZSTD_MODE = 1;
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Xlog() {
    return Xlog.fromReference(
        _new$(_class.reference.pointer, _id_new$ as _$jni.JMethodIDPtr)
            .reference);
  }

  static final _id_open = _class.staticMethodId(
    r'open',
    r'(ZIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _open = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void open(boolean z, int i, int i1, java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.String string3)`
  static void open(
    bool z,
    int i,
    int i1,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    _$jni.JString string3,
  ) {
    _open(
            _class.reference.pointer,
            _id_open as _$jni.JMethodIDPtr,
            z ? 1 : 0,
            i,
            i1,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            string3.reference.pointer)
        .check();
  }

  static final _id_logV = _class.instanceMethodId(
    r'logV',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logV = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void logV(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logV(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logV(
            reference.pointer,
            _id_logV as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logD = _class.instanceMethodId(
    r'logD',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logD = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void logD(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logD(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logD(
            reference.pointer,
            _id_logD as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logI = _class.instanceMethodId(
    r'logI',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logI = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void logI(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logI(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logI(
            reference.pointer,
            _id_logI as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logW = _class.instanceMethodId(
    r'logW',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logW = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void logW(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logW(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logW(
            reference.pointer,
            _id_logW as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logE = _class.instanceMethodId(
    r'logE',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logE = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void logE(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logE(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logE(
            reference.pointer,
            _id_logE as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_logF = _class.instanceMethodId(
    r'logF',
    r'(JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logF = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void logF(long j, java.lang.String string, java.lang.String string1, java.lang.String string2, int i, int i1, long j1, long j2, java.lang.String string3)`
  void logF(
    int j,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i,
    int i1,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logF(
            reference.pointer,
            _id_logF as _$jni.JMethodIDPtr,
            j,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i,
            i1,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_appenderOpen = _class.instanceMethodId(
    r'appenderOpen',
    r'(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V',
  );

  static final _appenderOpen = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int)>();

  /// from: `public void appenderOpen(int i, int i1, java.lang.String string, java.lang.String string1, java.lang.String string2, int i2)`
  void appenderOpen(
    int i,
    int i1,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i2,
  ) {
    _appenderOpen(
            reference.pointer,
            _id_appenderOpen as _$jni.JMethodIDPtr,
            i,
            i1,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i2)
        .check();
  }

  static final _id_logWrite = _class.staticMethodId(
    r'logWrite',
    r'(Lcom/tencent/mars/xlog/Xlog$XLoggerInfo;Ljava/lang/String;)V',
  );

  static final _logWrite = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public native void logWrite(com.tencent.mars.xlog.Xlog$XLoggerInfo xLoggerInfo, java.lang.String string)`
  static void logWrite(
    _$jni.JObject xLoggerInfo,
    _$jni.JString string,
  ) {
    _logWrite(_class.reference.pointer, _id_logWrite as _$jni.JMethodIDPtr,
            xLoggerInfo.reference.pointer, string.reference.pointer)
        .check();
  }

  static final _id_logWrite2 = _class.staticMethodId(
    r'logWrite2',
    r'(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logWrite2 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public void logWrite2(int i, java.lang.String string, java.lang.String string1, java.lang.String string2, int i1, int i2, long j, long j1, java.lang.String string3)`
  static void logWrite2(
    int i,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i1,
    int i2,
    int j,
    int j1,
    _$jni.JString string3,
  ) {
    _logWrite2(
            _class.reference.pointer,
            _id_logWrite2 as _$jni.JMethodIDPtr,
            i,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i1,
            i2,
            j,
            j1,
            string3.reference.pointer)
        .check();
  }

  static final _id_logWrite2$1 = _class.staticMethodId(
    r'logWrite2',
    r'(JILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIJJLjava/lang/String;)V',
  );

  static final _logWrite2$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int64,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int64,
                        _$jni.Int64,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public native void logWrite2(long j, int i, java.lang.String string, java.lang.String string1, java.lang.String string2, int i1, int i2, long j1, long j2, java.lang.String string3)`
  static void logWrite2$1(
    int j,
    int i,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i1,
    int i2,
    int j1,
    int j2,
    _$jni.JString string3,
  ) {
    _logWrite2$1(
            _class.reference.pointer,
            _id_logWrite2$1 as _$jni.JMethodIDPtr,
            j,
            i,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i1,
            i2,
            j1,
            j2,
            string3.reference.pointer)
        .check();
  }

  static final _id_getLogLevel = _class.instanceMethodId(
    r'getLogLevel',
    r'(J)I',
  );

  static final _getLogLevel = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<(_$jni.Int64,)>)>>('globalEnv_CallIntMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int)>();

  /// from: `public native int getLogLevel(long j)`
  int getLogLevel(
    int j,
  ) {
    return _getLogLevel(
            reference.pointer, _id_getLogLevel as _$jni.JMethodIDPtr, j)
        .integer;
  }

  static final _id_setAppenderMode = _class.instanceMethodId(
    r'setAppenderMode',
    r'(JI)V',
  );

  static final _setAppenderMode = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public native void setAppenderMode(long j, int i)`
  void setAppenderMode(
    int j,
    int i,
  ) {
    _setAppenderMode(
            reference.pointer, _id_setAppenderMode as _$jni.JMethodIDPtr, j, i)
        .check();
  }

  static final _id_openLogInstance = _class.instanceMethodId(
    r'openLogInstance',
    r'(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)J',
  );

  static final _openLogInstance = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32
                      )>)>>('globalEnv_CallLongMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              int,
              int,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>,
              int)>();

  /// from: `public long openLogInstance(int i, int i1, java.lang.String string, java.lang.String string1, java.lang.String string2, int i2)`
  int openLogInstance(
    int i,
    int i1,
    _$jni.JString string,
    _$jni.JString string1,
    _$jni.JString string2,
    int i2,
  ) {
    return _openLogInstance(
            reference.pointer,
            _id_openLogInstance as _$jni.JMethodIDPtr,
            i,
            i1,
            string.reference.pointer,
            string1.reference.pointer,
            string2.reference.pointer,
            i2)
        .long;
  }

  static final _id_getXlogInstance = _class.instanceMethodId(
    r'getXlogInstance',
    r'(Ljava/lang/String;)J',
  );

  static final _getXlogInstance = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JniResult Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallLongMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public native long getXlogInstance(java.lang.String string)`
  int getXlogInstance(
    _$jni.JString string,
  ) {
    return _getXlogInstance(reference.pointer,
            _id_getXlogInstance as _$jni.JMethodIDPtr, string.reference.pointer)
        .long;
  }

  static final _id_releaseXlogInstance = _class.instanceMethodId(
    r'releaseXlogInstance',
    r'(Ljava/lang/String;)V',
  );

  static final _releaseXlogInstance = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public native void releaseXlogInstance(java.lang.String string)`
  void releaseXlogInstance(
    _$jni.JString string,
  ) {
    _releaseXlogInstance(
            reference.pointer,
            _id_releaseXlogInstance as _$jni.JMethodIDPtr,
            string.reference.pointer)
        .check();
  }

  static final _id_newXlogInstance = _class.instanceMethodId(
    r'newXlogInstance',
    r'(Lcom/tencent/mars/xlog/Xlog$XLogConfig;)J',
  );

  static final _newXlogInstance = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JniResult Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallLongMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public native long newXlogInstance(com.tencent.mars.xlog.Xlog$XLogConfig xLogConfig)`
  int newXlogInstance(
    Xlog_XLogConfig xLogConfig,
  ) {
    return _newXlogInstance(
            reference.pointer,
            _id_newXlogInstance as _$jni.JMethodIDPtr,
            xLogConfig.reference.pointer)
        .long;
  }

  static final _id_setConsoleLogOpen = _class.instanceMethodId(
    r'setConsoleLogOpen',
    r'(JZ)V',
  );

  static final _setConsoleLogOpen = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public native void setConsoleLogOpen(long j, boolean z)`
  void setConsoleLogOpen(
    int j,
    bool z,
  ) {
    _setConsoleLogOpen(reference.pointer,
            _id_setConsoleLogOpen as _$jni.JMethodIDPtr, j, z ? 1 : 0)
        .check();
  }

  static final _id_appenderClose = _class.instanceMethodId(
    r'appenderClose',
    r'()V',
  );

  static final _appenderClose = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public native void appenderClose()`
  void appenderClose() {
    _appenderClose(reference.pointer, _id_appenderClose as _$jni.JMethodIDPtr)
        .check();
  }

  static final _id_appenderFlush = _class.instanceMethodId(
    r'appenderFlush',
    r'(JZ)V',
  );

  static final _appenderFlush = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public native void appenderFlush(long j, boolean z)`
  void appenderFlush(
    int j,
    bool z,
  ) {
    _appenderFlush(reference.pointer, _id_appenderFlush as _$jni.JMethodIDPtr,
            j, z ? 1 : 0)
        .check();
  }

  static final _id_setMaxFileSize = _class.instanceMethodId(
    r'setMaxFileSize',
    r'(JJ)V',
  );

  static final _setMaxFileSize = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int64)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public native void setMaxFileSize(long j, long j1)`
  void setMaxFileSize(
    int j,
    int j1,
  ) {
    _setMaxFileSize(
            reference.pointer, _id_setMaxFileSize as _$jni.JMethodIDPtr, j, j1)
        .check();
  }

  static final _id_setMaxAliveTime = _class.instanceMethodId(
    r'setMaxAliveTime',
    r'(JJ)V',
  );

  static final _setMaxAliveTime = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Int64, _$jni.Int64)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int, int)>();

  /// from: `public native void setMaxAliveTime(long j, long j1)`
  void setMaxAliveTime(
    int j,
    int j1,
  ) {
    _setMaxAliveTime(
            reference.pointer, _id_setMaxAliveTime as _$jni.JMethodIDPtr, j, j1)
        .check();
  }
}

final class $Xlog$Type extends _$jni.JObjType<Xlog> {
  @_$jni.internal
  const $Xlog$Type();

  @_$jni.internal
  @_$core.override
  String get signature => r'Lcom/tencent/mars/xlog/Xlog;';

  @_$jni.internal
  @_$core.override
  Xlog fromReference(_$jni.JReference reference) =>
      Xlog.fromReference(reference);

  @_$jni.internal
  @_$core.override
  _$jni.JObjType get superType => const _$jni.JObjectType();

  @_$jni.internal
  @_$core.override
  final superCount = 1;

  @_$core.override
  int get hashCode => ($Xlog$Type).hashCode;

  @_$core.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Xlog$Type) && other is $Xlog$Type;
  }
}
